language: ruby
rvm:
- 2.3.1
- 2.3.4
- 2.4.2
gemfile:
- gemfiles/activesupport-5.1.gemfile
before_install:
- gem install bundler
notifications:
  email:
    on_success: never
  slack:
    secure: albCNzaNaP6ixh4Wcb+m5JTxVaROyO89AK7iN4EU11nbV1k33dbr4e6Csd16AI+PBqEm5wKVaU58DjYTtDR30led2WhZFJXda6Y1fzxLM/QdNUmtcSzgEh0vjmj83GN6LXSMcY5vR572LwLH8Zf/nT3rJ36K3nt6oQNnEAoXfJM=
