language: ruby
rvm:
  - 2.0.0
  - 2.1.1
  - 2.3.1

gemfile:
  - gemfiles/activesupport-3.2.gemfile
  - gemfiles/activesupport-4.0.gemfile
  - gemfiles/activesupport-4.1.gemfile
  - gemfiles/activesupport-4.2.gemfile

before_install:
  - gem install bundler
