language: ruby
rvm:
- 2.5
- 2.6
- 2.7
gemfile:
- gemfiles/activesupport-5.2.gemfile
- gemfiles/activesupport-6.0.gemfile
matrix:
  exclude: []
before_install:
- gem install bundler
notifications:
  email:
    on_success: never
  slack:
    secure: albCNzaNaP6ixh4Wcb+m5JTxVaROyO89AK7iN4EU11nbV1k33dbr4e6Csd16AI+PBqEm5wKVaU58DjYTtDR30led2WhZFJXda6Y1fzxLM/QdNUmtcSzgEh0vjmj83GN6LXSMcY5vR572LwLH8Zf/nT3rJ36K3nt6oQNnEAoXfJM=
